// Country and language lists used by the quote form builder (country restriction,
// the storefront country select and the "Add new language" picker). Extracted from
// the production app's constant/country.js and constant/graphqlLanguages.js.

export const COUNTRIES = [
  ["AF", "Afghanistan"],
  ["AL", "Albania"],
  ["DZ", "Algeria"],
  ["AS", "American Samoa"],
  ["AD", "Andorra"],
  ["AO", "Angola"],
  ["AI", "Anguilla"],
  ["AG", "Antigua and Barbuda"],
  ["AR", "Argentina"],
  ["AM", "Armenia"],
  ["AW", "Aruba"],
  ["AU", "Australia"],
  ["AT", "Austria"],
  ["AZ", "Azerbaijan"],
  ["BS", "Bahamas"],
  ["BH", "Bahrain"],
  ["BD", "Bangladesh"],
  ["BB", "Barbados"],
  ["BY", "Belarus"],
  ["BE", "Belgium"],
  ["BZ", "Belize"],
  ["BJ", "Benin"],
  ["BM", "Bermuda"],
  ["BT", "Bhutan"],
  ["BO", "Bolivia (Plurinational State of)"],
  ["BA", "Bosnia and Herzegovina"],
  ["BW", "Botswana"],
  ["BR", "Brazil"],
  ["IO", "British Indian Ocean Territory"],
  ["VG", "Virgin Islands (British)"],
  ["VI", "Virgin Islands (U.S.)"],
  ["BN", "Brunei Darussalam"],
  ["BG", "Bulgaria"],
  ["BF", "Burkina Faso"],
  ["BI", "Burundi"],
  ["KH", "Cambodia"],
  ["CM", "Cameroon"],
  ["CA", "Canada"],
  ["CV", "Cabo Verde"],
  ["KY", "Cayman Islands"],
  ["CF", "Central African Republic"],
  ["CL", "Chile"],
  ["CN", "China"],
  ["CO", "Colombia"],
  ["KM", "Comoros"],
  ["CG", "Congo"],
  ["CD", "Congo (Democratic Republic of the)"],
  ["CK", "Cook Islands"],
  ["CR", "Costa Rica"],
  ["HR", "Croatia"],
  ["CU", "Cuba"],
  ["CY", "Cyprus"],
  ["CZ", "Czech Republic"],
  ["DK", "Denmark"],
  ["DJ", "Djibouti"],
  ["DM", "Dominica"],
  ["DO", "Dominican Republic"],
  ["EC", "Ecuador"],
  ["EG", "Egypt"],
  ["SV", "El Salvador"],
  ["GQ", "Equatorial Guinea"],
  ["ER", "Eritrea"],
  ["EE", "Estonia"],
  ["ET", "Ethiopia"],
  ["FK", "Falkland Islands (Malvinas)"],
  ["FO", "Faroe Islands"],
  ["FJ", "Fiji"],
  ["FI", "Finland"],
  ["FR", "France"],
  ["GF", "French Guiana"],
  ["PF", "French Polynesia"],
  ["GA", "Gabon"],
  ["GM", "Gambia"],
  ["GE", "Georgia"],
  ["DE", "Germany"],
  ["GH", "Ghana"],
  ["GI", "Gibraltar"],
  ["GR", "Greece"],
  ["GL", "Greenland"],
  ["GD", "Grenada"],
  ["GP", "Guadeloupe"],
  ["GU", "Guam"],
  ["GT", "Guatemala"],
  ["GN", "Guinea"],
  ["GW", "Guinea-Bissau"],
  ["GY", "Guyana"],
  ["HT", "Haiti"],
  ["VA", "Holy See"],
  ["HN", "Honduras"],
  ["HK", "Hong Kong"],
  ["HU", "Hungary"],
  ["IS", "Iceland"],
  ["IN", "India"],
  ["ID", "Indonesia"],
  ["CI", "Côte d'Ivoire"],
  ["IR", "Iran (Islamic Republic of)"],
  ["IQ", "Iraq"],
  ["IE", "Ireland"],
  ["IL", "Israel"],
  ["IT", "Italy"],
  ["JM", "Jamaica"],
  ["JP", "Japan"],
  ["JO", "Jordan"],
  ["KZ", "Kazakhstan"],
  ["KE", "Kenya"],
  ["KI", "Kiribati"],
  ["KW", "Kuwait"],
  ["KG", "Kyrgyzstan"],
  ["LA", "Lao People's Democratic Republic"],
  ["LV", "Latvia"],
  ["LB", "Lebanon"],
  ["LS", "Lesotho"],
  ["LR", "Liberia"],
  ["LY", "Libya"],
  ["LI", "Liechtenstein"],
  ["LT", "Lithuania"],
  ["LU", "Luxembourg"],
  ["MO", "Macao"],
  ["MK", "Macedonia (the former Yugoslav Republic of)"],
  ["MG", "Madagascar"],
  ["MW", "Malawi"],
  ["MY", "Malaysia"],
  ["MV", "Maldives"],
  ["ML", "Mali"],
  ["MT", "Malta"],
  ["MH", "Marshall Islands"],
  ["MQ", "Martinique"],
  ["MR", "Mauritania"],
  ["MU", "Mauritius"],
  ["YT", "Mayotte"],
  ["MX", "Mexico"],
  ["FM", "Micronesia (Federated States of)"],
  ["MD", "Moldova (Republic of)"],
  ["MC", "Monaco"],
  ["MN", "Mongolia"],
  ["ME", "Montenegro"],
  ["MS", "Montserrat"],
  ["MA", "Morocco"],
  ["MZ", "Mozambique"],
  ["MM", "Myanmar"],
  ["NA", "Namibia"],
  ["NR", "Nauru"],
  ["NP", "Nepal"],
  ["NL", "Netherlands"],
  ["NC", "New Caledonia"],
  ["NZ", "New Zealand"],
  ["NI", "Nicaragua"],
  ["NE", "Niger"],
  ["NG", "Nigeria"],
  ["NU", "Niue"],
  ["NF", "Norfolk Island"],
  ["KP", "Korea (Democratic People's Republic of)"],
  ["MP", "Northern Mariana Islands"],
  ["NO", "Norway"],
  ["OM", "Oman"],
  ["PK", "Pakistan"],
  ["PW", "Palau"],
  ["PS", "Palestine, State of"],
  ["PA", "Panama"],
  ["PG", "Papua New Guinea"],
  ["PY", "Paraguay"],
  ["PE", "Peru"],
  ["PH", "Philippines"],
  ["PL", "Poland"],
  ["PT", "Portugal"],
  ["PR", "Puerto Rico"],
  ["QA", "Qatar"],
  ["XK", "Republic of Kosovo"],
  ["RE", "Réunion"],
  ["RO", "Romania"],
  ["RU", "Russian Federation"],
  ["RW", "Rwanda"],
  ["BL", "Saint Barthélemy"],
  ["SH", "Saint Helena, Ascension and Tristan da Cunha"],
  ["KN", "Saint Kitts and Nevis"],
  ["LC", "Saint Lucia"],
  ["MF", "Saint Martin (French part)"],
  ["PM", "Saint Pierre and Miquelon"],
  ["VC", "Saint Vincent and the Grenadines"],
  ["WS", "Samoa"],
  ["SM", "San Marino"],
  ["ST", "Sao Tome and Principe"],
  ["SA", "Saudi Arabia"],
  ["SN", "Senegal"],
  ["RS", "Serbia"],
  ["SC", "Seychelles"],
  ["SL", "Sierra Leone"],
  ["SG", "Singapore"],
  ["SK", "Slovakia"],
  ["SI", "Slovenia"],
  ["SB", "Solomon Islands"],
  ["SO", "Somalia"],
  ["ZA", "South Africa"],
  ["KR", "Korea (Republic of)"],
  ["ES", "Spain"],
  ["LK", "Sri Lanka"],
  ["SD", "Sudan"],
  ["SR", "Suriname"],
  ["SZ", "Swaziland"],
  ["SE", "Sweden"],
  ["CH", "Switzerland"],
  ["SY", "Syrian Arab Republic"],
  ["TW", "Taiwan"],
  ["TJ", "Tajikistan"],
  ["TZ", "Tanzania, United Republic of"],
  ["TH", "Thailand"],
  ["TL", "Timor-Leste"],
  ["TG", "Togo"],
  ["TK", "Tokelau"],
  ["TO", "Tonga"],
  ["TT", "Trinidad and Tobago"],
  ["TN", "Tunisia"],
  ["TR", "Turkey"],
  ["TM", "Turkmenistan"],
  ["TC", "Turks and Caicos Islands"],
  ["TV", "Tuvalu"],
  ["UG", "Uganda"],
  ["UA", "Ukraine"],
  ["AE", "United Arab Emirates"],
  ["GB", "United Kingdom of Great Britain and Northern Ireland"],
  ["US", "United States of America"],
  ["UY", "Uruguay"],
  ["UZ", "Uzbekistan"],
  ["VU", "Vanuatu"],
  ["VE", "Venezuela (Bolivarian Republic of)"],
  ["VN", "Viet Nam"],
  ["WF", "Wallis and Futuna"],
  ["YE", "Yemen"],
  ["ZM", "Zambia"],
  ["ZW", "Zimbabwe"],
];

export const LANGUAGES = [
  ["AF", "Afrikaans"],
  ["AK", "Akan"],
  ["AM", "Amharic"],
  ["AR", "Arabic"],
  ["AS", "Assamese"],
  ["AZ", "Azerbaijani"],
  ["BE", "Belarusian"],
  ["BG", "Bulgarian"],
  ["BM", "Bambara"],
  ["BN", "Bangla"],
  ["BO", "Tibetan"],
  ["BR", "Breton"],
  ["BS", "Bosnian"],
  ["CA", "Catalan"],
  ["CE", "Chechen"],
  ["CKB", "Central Kurdish"],
  ["CS", "Czech"],
  ["CU", "Church Slavic"],
  ["CY", "Welsh"],
  ["DA", "Danish"],
  ["DE", "German"],
  ["DZ", "Dzongkha"],
  ["EE", "Ewe"],
  ["EL", "Greek"],
  ["EN", "English"],
  ["EO", "Esperanto"],
  ["ES", "Spanish"],
  ["ET", "Estonian"],
  ["EU", "Basque"],
  ["FA", "Persian"],
  ["FF", "Fulah"],
  ["FI", "Finnish"],
  ["FIL", "Filipino"],
  ["FO", "Faroese"],
  ["FR", "French"],
  ["FY", "Western Frisian"],
  ["GA", "Irish"],
  ["GD", "Scottish Gaelic"],
  ["GL", "Galician"],
  ["GU", "Gujarati"],
  ["GV", "Manx"],
  ["HA", "Hausa"],
  ["HE", "Hebrew"],
  ["HI", "Hindi"],
  ["HR", "Croatian"],
  ["HU", "Hungarian"],
  ["HY", "Armenian"],
  ["IA", "Interlingua"],
  ["ID", "Indonesian"],
  ["IG", "Igbo"],
  ["II", "Sichuan Yi"],
  ["IS", "Icelandic"],
  ["IT", "Italian"],
  ["JA", "Japanese"],
  ["JV", "Javanese"],
  ["KA", "Georgian"],
  ["KI", "Kikuyu"],
  ["KK", "Kazakh"],
  ["KL", "Kalaallisut"],
  ["KM", "Khmer"],
  ["KN", "Kannada"],
  ["KO", "Korean"],
  ["KS", "Kashmiri"],
  ["KU", "Kurdish"],
  ["KW", "Cornish"],
  ["KY", "Kyrgyz"],
  ["LA", "Latin"],
  ["LB", "Luxembourgish"],
  ["LG", "Ganda"],
  ["LN", "Lingala"],
  ["LO", "Lao"],
  ["LT", "Lithuanian"],
  ["LU", "Luba-Katanga"],
  ["LV", "Latvian"],
  ["MG", "Malagasy"],
  ["MI", "Māori"],
  ["MK", "Macedonian"],
  ["ML", "Malayalam"],
  ["MN", "Mongolian"],
  ["MO", "Moldavian"],
  ["MR", "Marathi"],
  ["MS", "Malay"],
  ["MT", "Maltese"],
  ["MY", "Burmese"],
  ["NB", "Norwegian (Bokmål)"],
  ["ND", "North Ndebele"],
  ["NE", "Nepali"],
  ["NL", "Dutch"],
  ["NN", "Norwegian Nynorsk"],
  ["NO", "Norwegian"],
  ["OM", "Oromo"],
  ["OR", "Odia"],
  ["OS", "Ossetic"],
  ["PA", "Punjabi"],
  ["PL", "Polish"],
  ["PS", "Pashto"],
  ["PT", "Portuguese"],
  ["PT_BR", "Portuguese (Brazil)"],
  ["PT_PT", "Portuguese (Portugal)"],
  ["QU", "Quechua"],
  ["RM", "Romansh"],
  ["RN", "Rundi"],
  ["RO", "Romanian"],
  ["RU", "Russian"],
  ["RW", "Kinyarwanda"],
  ["SA", "Sanskrit"],
  ["SC", "Sardinian"],
  ["SD", "Sindhi"],
  ["SE", "Northern Sami"],
  ["SG", "Sango"],
  ["SH", "Serbo-Croatian"],
  ["SI", "Sinhala"],
  ["SK", "Slovak"],
  ["SL", "Slovenian"],
  ["SN", "Shona"],
  ["SO", "Somali"],
  ["SQ", "Albanian"],
  ["SR", "Serbian"],
  ["SU", "Sundanese"],
  ["SV", "Swedish"],
  ["SW", "Swahili"],
  ["TA", "Tamil"],
  ["TE", "Telugu"],
  ["TG", "Tajik"],
  ["TH", "Thai"],
  ["TI", "Tigrinya"],
  ["TK", "Turkmen"],
  ["TO", "Tongan"],
  ["TR", "Turkish"],
  ["TT", "Tatar"],
  ["UG", "Uyghur"],
  ["UK", "Ukrainian"],
  ["UR", "Urdu"],
  ["UZ", "Uzbek"],
  ["VI", "Vietnamese"],
  ["VO", "Volapük"],
  ["WO", "Wolof"],
  ["XH", "Xhosa"],
  ["YI", "Yiddish"],
  ["YO", "Yoruba"],
  ["ZH", "Chinese"],
  ["ZH_CN", "Chinese (Simplified)"],
  ["ZH_TW", "Chinese (Traditional)"],
  ["ZU", "Zulu"],
];

// constant/country.js listPhoneCountry → [code, country, dial code]; the storefront
// phone selects list them as "Country (+code)" (phoneCountryOptions).
export const PHONE_COUNTRIES = [
  ["AF","Afghanistan","+93"],
  ["AL","Albania","+355"],
  ["DZ","Algeria","+213"],
  ["AS","American Samoa","+1648"],
  ["AD","Andorra","+376"],
  ["AO","Angola","+244"],
  ["AI","Anguilla","+1"],
  ["AG","Antigua and Barbuda","+1268"],
  ["AR","Argentina","+54"],
  ["AM","Armenia","+374"],
  ["AW","Aruba","+297"],
  ["AC","Ascension","+1"],
  ["AU","Australia","+61"],
  ["AT","Austria","+43"],
  ["AZ","Azerbaijan","+944"],
  ["BS","Bahamas","+1242"],
  ["BH","Bahrain","+973"],
  ["BD","Bangladesh","+880"],
  ["BB","Barbados","+1246"],
  ["BY","Belarus","+375"],
  ["BE","Belgium","+32"],
  ["BZ","Belize","+501"],
  ["BJ","Benin","+229"],
  ["BM","Bermuda","+1441"],
  ["BT","Bhutan","+975"],
  ["BO","Bolivia","+591"],
  ["BQ","Bonaire, Sabo & St. Eustacius","+599"],
  ["BA","Bosnia and Herzegovina","+387"],
  ["BW","Botswana","+267"],
  ["BR","Brazil","+55"],
  ["VG","British Virgin Islands","+1-284"],
  ["BN","Brunei Darussalam","+673"],
  ["BG","Bulgaria","+1340"],
  ["BF","Burkina Faso","+226"],
  ["BI","Burundi","+257"],
  ["KH","Cambodia","+855"],
  ["CM","Cameroon","+237"],
  ["CA","Canada","+1"],
  ["CV","Cape Verde","+238"],
  ["KY","Cayman Islands","+1"],
  ["CF","Central African Republic","+236"],
  ["TD","Chad","+235"],
  ["CL","Chile","+56"],
  ["CN","China","+86"],
  ["CO","Colombia","+57"],
  ["KM","Comoros","+269"],
  ["CG","Congo","+242"],
  ["CK","Cook Islands","+682"],
  ["CR","Costa Rica","+506"],
  ["CI","Cote d'Ivoire","+225"],
  ["HR","Croatia","+385"],
  ["CU","Cuba","+53"],
  ["CW","Curacao","+599"],
  ["CY","Cyprus","+357"],
  ["CZ","Czech Republic","+420"],
  ["CD","Democratic Republic of the Congo","+243"],
  ["DK","Denmark","+45"],
  ["DG","Diego Garcia","+246"],
  ["DJ","Djibouti","+253"],
  ["DM","Dominica","+1767"],
  ["DO","Dominican Republic","+1809"],
  ["TL","East Timor","+670"],
  ["EC","Ecuador","+593"],
  ["EG","Egypt","+20"],
  ["SV","El Salvador","+503"],
  ["GQ","Equatorial Guinea","+240"],
  ["ER","Eritrea","+291"],
  ["EE","Estonia","+372"],
  ["ET","Ethiopia","+251"],
  ["FK","Falkland Islands","+500"],
  ["FO","Faroe Islands","+298"],
  ["FJ","Fiji","+679"],
  ["FI","Finland","+358"],
  ["FR","France","+33"],
  ["GF","French Guiana","+594"],
  ["PF","French Polynesia","+689"],
  ["GA","Gabon","+241"],
  ["GM","Gambia","+220"],
  ["GE","Georgia","+995"],
  ["DE","Germany","+49"],
  ["GH","Ghana","+233"],
  ["GI","Gibraltar","+350"],
  ["GR","Greece","+30"],
  ["GL","Greenland","+30"],
  ["GD","Grenada","+1473"],
  ["GP","Guadeloupe","+590"],
  ["GU","Guam","+1671"],
  ["GT","Guatemala","+502"],
  ["GN","Guinea","+224"],
  ["GW","Guinea-Bissau","+245"],
  ["GY","Guyana","+592"],
  ["HT","Haiti","+509"],
  ["HN","Honduras","+504"],
  ["HK","Hong Kong","+852"],
  ["HU","Hungary","+36"],
  ["IS","Iceland","+354"],
  ["IN","India","+91"],
  ["ID","Indonesia","+62"],
  ["IR","Iran","+98"],
  ["IQ","Iraq","+964"],
  ["IE","Ireland","+353"],
  ["IL","Israel","+972"],
  ["IT","Italy","+39"],
  ["JM","Jamaica","+1876"],
  ["JP","Japan","+81"],
  ["JO","Jordan","+962"],
  ["KZ","Kazakhstan","+7"],
  ["KE","Kenya","+254"],
  ["KI","Kiribati","+686"],
  ["KW","Kuwait","+965"],
  ["KG","Kyrgyzstan","+996"],
  ["LA","Lao","+856"],
  ["LV","Latvia","+371"],
  ["LB","Lebanon","+961"],
  ["LS","Lesotho","+266"],
  ["LR","Liberia","+231"],
  ["LY","Libya","+218"],
  ["LI","Liechtenstein","+423"],
  ["LT","Lithuania","+370"],
  ["LU","Luxembourg","+352"],
  ["MO","Macao","+853"],
  ["MK","Macedonia","+389"],
  ["MG","Madagascar","+261"],
  ["MW","Malawi","+265"],
  ["MY","Malaysia","+60"],
  ["MV","Maldives","+960"],
  ["ML","Mali","+223"],
  ["MT","Malta","+356"],
  ["MH","Marshall Islands","+692"],
  ["MQ","Martinique","+596"],
  ["MR","Mauritania","+222"],
  ["MU","Mauritius","+230"],
  ["YT","Mayotte","+262"],
  ["MX","Mexico","+52"],
  ["FM","Micronesia","+691"],
  ["MD","Moldova","+373"],
  ["MC","Monaco","+377"],
  ["MN","Mongolia","+976"],
  ["ME","Montenegro","+382"],
  ["MS","Montserrat","+1664"],
  ["MA","Morocco","+212"],
  ["MZ","Mozambique","+258"],
  ["MM","Myanmar","+95"],
  ["NA","Namibia","+264"],
  ["NR","Nauru","+674"],
  ["NP","Nepal","+977"],
  ["NL","Netherlands","+31"],
  ["NC","New Caledonia","+687"],
  ["NZ","New Zealand","+64"],
  ["NI","Nicaragua","+505"],
  ["NE","Niger","+227"],
  ["NG","Nigeria","+234"],
  ["NU","Niue","+683"],
  ["NF","Norfolk Island","+672"],
  ["MP","Northern Mariana Islands","+1"],
  ["NO","Norway","+47"],
  ["OM","Oman","+968"],
  ["PK","Pakistan","+92"],
  ["PW","Palau","+680"],
  ["PS","Palestine","+970"],
  ["PA","Panama","+507"],
  ["PG","Papua New Guinea","+675"],
  ["PY","Paraguay","+595"],
  ["PE","Peru","+51"],
  ["PH","Philippines","+63"],
  ["PL","Poland","+48"],
  ["PT","Portugal","+351"],
  ["PR","Puerto Rico","+1787"],
  ["QA","Qatar","+974"],
  ["RE","Reunion","+262"],
  ["RO","Romania","+40"],
  ["RU","Russia","+7"],
  ["RW","Rwanda","+250"],
  ["SH","Saint Helena","+290"],
  ["KN","Saint Kitts and Nevis","+1869"],
  ["LC","Saint Lucia","+1758"],
  ["PM","Saint Pierre and Miquelon","+508"],
  ["VC","Saint Vincent and the Grenadines","+1784"],
  ["WS","Samoa","+685"],
  ["SM","San Marino","+378"],
  ["ST","Sao Tome and Principe","+239"],
  ["SA","Saudi Arabia","+966"],
  ["SN","Senegal","+221"],
  ["RS","Serbia","+381"],
  ["SC","Seychelles","+248"],
  ["SL","Sierra Leone","+232"],
  ["SG","Singapore","+65"],
  ["SX","Sint Maarten","+721"],
  ["SK","Slovakia","+421"],
  ["SI","Slovenia","+386"],
  ["SB","Solomon Islands","+677"],
  ["SO","Somalia","+252"],
  ["ZA","South Africa","+27"],
  ["KR","South Korea","+82"],
  ["SS","South Sudan","+211"],
  ["ES","Spain","+34"],
  ["LK","Sri Lanka","+94"],
  ["SD","Sudan","+249"],
  ["SR","Suriname","+597"],
  ["SZ","Swaziland","+268"],
  ["SE","Sweden","+46"],
  ["CH","Switzerland","+41"],
  ["SY","Syria","+963"],
  ["TW","Taiwan","+886"],
  ["TJ","Tajikistan","+992"],
  ["TZ","Tanzania","+255"],
  ["TH","Thailand","+66"],
  ["TG","Togo","+228"],
  ["TK","Tokelau","+690"],
  ["TO","Tonga","+676"],
  ["TT","Trinidad and Tobago","+1868"],
  ["TN","Tunisia","+216"],
  ["TR","Turkey","+90"],
  ["TM","Turkmenistan","+993"],
  ["TC","Turks and Caicos Islands","+1"],
  ["TV","Tuvalu","+688"],
  ["VI","U.S. Virgin Islands","+1"],
  ["UG","Uganda","+256"],
  ["UA","Ukraine","+380"],
  ["AE","United Arab Emirates","+971"],
  ["GB","United Kingdom","+44"],
  ["US","United States","+1"],
  ["UY","Uruguay","+598"],
  ["UZ","Uzbekistan","+998"],
  ["VU","Vanuatu","+678"],
  ["VA","Vatican City State","+379"],
  ["VE","Venezuela","+58"],
  ["VN","Vietnam","+84"],
  ["WF","Wallis and Futuna","+681"],
  ["YE","Yemen","+967"],
  ["ZM","Zambia","+260"],
  ["ZW","Zimbabwe","+263"],
];
